
constants = {
    HTML_DOCTYPE_RE : /<!DOCTYPE.*?>/im,
    HTML_COMMENT_RE : /<!--(.*?)-->/m,
    HTML_INSTRUCTION_RE : /<\?(.*?)\?>/m,
    HTML_ATTRIBUTE_RE : /\s*(#{(?:[[:alpha:]_:][-[:alnum:]._:]*:)?[[:alpha:]_:][-[:alnum:]._:]*})(?:\s*=\s*(["'])(.*?)\2)?/m,
    HTML_TAG_RE : /<((?=(?:[[:alpha:]_:][-[:alnum:]._:]*:)?[[:alpha:]_:][-[:alnum:]._:]*))\s*((?=(\s+(?:[[:alpha:]_:][-[:alnum:]._:]*:)?[[:alpha:]_:][-[:alnum:]._:]*(?:\s*=\s*(["']).*?\3)?)*))\s*(\/)?>/m,
    HTML_TAG_CLOSE_RE : /<\/(#{(?:[[:alpha:]_:][-[:alnum:]._:]*:)?[[:alpha:]_:][-[:alnum:]._:]*})\s*>/m,
    HTML_ENTITY_RE : /&([\w:][\-\w\.:]*);|&#(\d+);|&\#x([0-9a-fA-F]+);/,
    HTML_CONTENT_MODEL_BLOCK : [
        "address", 
        "applet", 
        "article", 
        "aside", 
        "blockquote", 
        "body", 
        "dd", 
        "details", 
        "div", 
        "dl", 
        "fieldset", 
        "figure", 
        "figcaption", 
        "footer", 
        "form", 
        "header", 
        "hgroup", 
        "iframe", 
        "li", 
        "map", 
        "menu", 
        "nav", 
        "noscript", 
        "object", 
        "section", 
        "summary", 
        "td"
    ],

    HTML_CONTENT_MODEL_SPAN : [
        "a", 
        "abbr", 
        "acronym", 
        "b",
        "bdo", 
        "big", 
        "button", 
        "cite", 
        "caption", 
        "del", 
        "dfn", 
        "dt", 
        "em", 
        "h1", 
        "h2", 
        "h3", 
        "h4", 
        "h5", 
        "h6", 
        "i", 
        "ins", 
        "label", 
        "legend", 
        "optgroup", 
        "p", 
        "q", 
        "rb", 
        "rbc", 
        "rp", 
        "rt", 
        "rtc", 
        "ruby", 
        "select", 
        "small", 
        "span", 
        "strong", 
        "sub", 
        "sup", 
        "th", 
        "tt"
    ],

    HTML_CONTENT_MODEL_RAW : [
        "script", 
        "style", 
        "math", 
        "option", 
        "textarea", 
        "pre", 
        "code", 
        "kbd", 
        "samp", 
        "var"
    ],


    HTML_SPAN_ELEMENTS : [
        "a", 
        "abbr", 
        "acronym", 
        "b", 
        "big", 
        "bdo", 
        "br", 
        "button", 
        "cite", 
        "code", 
        "del", 
        "dfn", 
        "em", 
        "i", 
        "img", 
        "input", 
        "ins", 
        "kbd", 
        "label", 
        "mark", 
        "option", 
        "q", 
        "rb", 
        "rbc", 
        "rp", 
        "rt", 
        "rtc", 
        "ruby", 
        "samp", 
        "select", 
        "small", 
        "span", 
        "strong", 
        "sub", 
        "sup", 
        "tt", 
        "u", 
        "var"
    ],

    HTML_BLOCK_ELEMENTS : [
        "address", 
        "article", 
        "aside", 
        "applet", 
        "body", 
        "blockquote", 
        "caption", 
        "col", 
        "colgroup", 
        "dd", 
        "div", 
        "dl",
        "dt", 
        "fieldset",
        "figcaption", 
        "footer", 
        "form", 
        "h1", 
        "h2", 
        "h3", 
        "h4", 
        "h5", 
        "h6", 
        "header", 
        "hgroup", 
        "hr", 
        "html", 
        "head", 
        "iframe", 
        "legend", 
        "menu", 
        "li", 
        "map", 
        "nav", 
        "ol", 
        "optgroup", 
        "p", 
        "pre", 
        "section", 
        "summary", 
        "table", 
        "tbody", 
        "td", 
        "th", 
        "thead", 
        "tfoot",
        "tr", 
        "ul"
    ],

    HTML_ELEMENTS_WITHOUT_BODY : [
        "area", 
        "base", 
        "br", 
        "col", 
        "command", 
        "embed", 
        "hr", 
        "img", 
        "input", 
        "keygen",
        "link", 
        "meta", 
        "param", 
        "source", 
        "track", 
        "wbr"
    ],

    HTML_ELEMENT : {},
    HTML_CONTENT_MODEL : {},
    
    ENTITY_TABLE : {
        "338": 140,
        "339": 156,
        "352": 138,
        "353": 154,
        "376": 159,
        "381": 142,
        "382": 158,
        "402": 131,
        "710": 136,
        "732": 152,
        "8211": 150,
        "8212": 151,
        "8216": 145,
        "8217": 146,
        "8218": 130,
        "8220": 147,
        "8221": 148,
        "8222": 132,
        "8224": 134,
        "8225": 135,
        "8226": 149,
        "8230": 133,
        "8240": 137,
        "8249": 139,
        "8250": 155,
        "8364": 128,
        "8482": 153,
        "Alpha": 913,
        "Beta": 914,
        "Gamma": 915,
        "Delta": 916,
        "Epsilon": 917,
        "Zeta": 918,
        "Eta": 919,
        "Theta": 920,
        "Iota": 921,
        "Kappa": 922,
        "Lambda": 923,
        "Mu": 924,
        "Nu": 925,
        "Xi": 926,
        "Omicron": 927,
        "Pi": 928,
        "Rho": 929,
        "Sigma": 931,
        "Tau": 932,
        "Upsilon": 933,
        "Phi": 934,
        "Chi": 935,
        "Psi": 936,
        "Omega": 937,
        "alpha": 945,
        "beta": 946,
        "gamma": 947,
        "delta": 948,
        "epsilon": 949,
        "zeta": 950,
        "eta": 951,
        "theta": 952,
        "iota": 953,
        "kappa": 954,
        "lambda": 955,
        "mu": 956,
        "nu": 957,
        "xi": 958,
        "omicron": 959,
        "pi": 960,
        "rho": 961,
        "sigma": 963,
        "tau": 964,
        "upsilon": 965,
        "phi": 966,
        "chi": 967,
        "psi": 968,
        "omega": 969,
        "sigmaf": 962,
        "thetasym": 977,
        "upsih": 978,
        "piv": 982,
        "zwnj": 8204,
        "zwj": 8205,
        "lrm": 8206,
        "rlm": 8207,
        "hellip": 8230,
        "prime": 8242,
        "Prime": 8243,
        "oline": 8254,
        "frasl": 8260,
        "weierp": 8472,
        "image": 8465,
        "real": 8476,
        "alefsym": 8501,
        "bull": 8226,
        "trade": 8482,
        "larr": 8592,
        "rarr": 8594,
        "uarr": 8593,
        "darr": 8595,
        "harr": 8596,
        "crarr": 8629,
        "uArr": 8657,
        "dArr": 8659,
        "lArr": 8656,
        "rArr": 8658,
        "hArr": 8660,
        "forall": 8704,
        "part": 8706,
        "exist": 8707,
        "empty": 8709,
        "nabla": 8711,
        "isin": 8712,
        "ni": 8715,
        "notin": 8713,
        "sum": 8721,
        "prod": 8719,
        "minus": 8722,
        "lowast": 8727,
        "radic": 8730,
        "prop": 8733,
        "infin": 8734,
        "ang": 8736,
        "and": 8743,
        "or": 8744,
        "cup": 8745,
        "cap": 8746,
        "int": 8747,
        "there4": 8756,
        "sim": 8764,
        "asymp": 8776,
        "cong": 8773,
        "ne": 8800,
        "equiv": 8801,
        "le": 8804,
        "ge": 8805,
        "sub": 8834,
        "sup": 8835,
        "sube": 8838,
        "supe": 8839,
        "nsub": 8836,
        "oplus": 8853,
        "otimes": 8855,
        "perp": 8869,
        "sdot": 8901,
        "vellip": 8942,
        "rceil": 8968,
        "lceil": 8969,
        "lfloor": 8970,
        "rfloor": 8971,
        "rang": 9001,
        "lang": 9002,
        "loz": 9674,
        "spades": 9824,
        "clubs": 9827,
        "hearts": 9829,
        "diams": 9830,
        "amp": 38,
        "quot": 34,
        "apos": 39,
        "copy": 169,
        "lt": 60,
        "gt": 62,
        "OElig": 338,
        "oelig": 339,
        "Scaron": 352,
        "scaron": 353,
        "Yuml": 376,
        "circ": 710,
        "tilde": 732,
        "ndash": 8211,
        "mdash": 8212,
        "lsquo": 8216,
        "rsquo": 8217,
        "ldquo": 8220,
        "rdquo": 8221,
        "dagger": 8224,
        "Dagger": 8225,
        "permil": 8240,
        "euro": 8364,
        "lsaquo": 8249,
        "rsaquo": 8250,
        "nbsp": 160,
        "iexcl": 161,
        "pound": 163,
        "curren": 164,
        "yen": 165,
        "brvbar": 166,
        "sect": 167,
        "uml": 168,
        "laquo": 171,
        "raquo": 187,
        "reg": 174,
        "ordf": 170,
        "not": 172,
        "shy": 173,
        "macr": 175,
        "deg": 176,
        "plusmn": 177,
        "acute": 180,
        "micro": 181,
        "para": 182,
        "middot": 183,
        "cedil": 184,
        "ordm": 186,
        "cent": 162,
        "sup1": 185,
        "sup2": 178,
        "sup3": 179,
        "frac12": 189,
        "frac14": 188,
        "frac34": 190,
        "iquest": 191,
        "Agrave": 192,
        "Aacute": 193,
        "Acirc": 194,
        "Atilde": 195,
        "Auml": 196,
        "Aring": 197,
        "AElig": 198,
        "Ccedil": 199,
        "Egrave": 200,
        "Eacute": 201,
        "Ecirc": 202,
        "Euml": 203,
        "Igrave": 204,
        "Iacute": 205,
        "Icirc": 206,
        "Iuml": 207,
        "ETH": 208,
        "Ntilde": 209,
        "Ograve": 210,
        "Oacute": 211,
        "Ocirc": 212,
        "Otilde": 213,
        "Ouml": 214,
        "times": 215,
        "Oslash": 216,
        "Ugrave": 217,
        "Uacute": 218,
        "Ucirc": 219,
        "Uuml": 220,
        "Yacute": 221,
        "THORN": 222,
        "szlig": 223,
        "agrave": 224,
        "aacute": 225,
        "acirc": 226,
        "atilde": 227,
        "auml": 228,
        "aring": 229,
        "aelig": 230,
        "ccedil": 231,
        "egrave": 232,
        "eacute": 233,
        "ecirc": 234,
        "euml": 235,
        "igrave": 236,
        "iacute": 237,
        "icirc": 238,
        "iuml": 239,
        "eth": 240,
        "ntilde": 241,
        "ograve": 242,
        "oacute": 243,
        "ocirc": 244,
        "otilde": 245,
        "ouml": 246,
        "divide": 247,
        "oslash": 248,
        "ugrave": 249,
        "uacute": 250,
        "ucirc": 251,
        "uuml": 252,
        "yacute": 253,
        "thorn": 254,
        "yuml": 255,
        "sbquo": 8218,
        "fnof": 402,
        "bdquo": 8222,
        "ensp": 8194,
        "emsp": 8195,
        "thinsp": 8201
    },
    TYPOGRAPHIC_SYMS : {
        "mdash" : String.fromCodePoint(8212),
        "ndash" : String.fromCodePoint(8211),
        "hellip" : String.fromCodePoint(8230),
        "laquo_space" : String.fromCodePoint(171) + String.fromCodePoint(160),
        "raquo_space" : String.fromCodePoint(160) + String.fromCodePoint(187),
        "laquo" : String.fromCodePoint(171),
        "raquo" : String.fromCodePoint(187)
    },
    ESCAPE_RE_FROM_TYPE : {
        "all" : /<|>|&/,
        "text" : /^(?:((?=(mix:&(?:([\w:][\-\w\.:]*);|#\d+;|#x[0-9a-fA-F]+;)))\1)|(<|>|&))$/,
        "attribute" : /^(?:((?=(mix:&(?:([\w:][\-\w\.:]*);|#\d+;|#x[0-9a-fA-F]+;)))\1)|(<|>|&|"))$/
      }
};

//Populate HTML_CONTENT_MODEL
constants.HTML_CONTENT_MODEL_BLOCK.forEach(function(entry) {
    constants.HTML_CONTENT_MODEL[entry] = "block";
});

constants.HTML_CONTENT_MODEL_SPAN.forEach(function(entry) {
    constants.HTML_CONTENT_MODEL[entry] = "span";
});

constants.HTML_CONTENT_MODEL_RAW.forEach(function(entry) {
    constants.HTML_CONTENT_MODEL[entry] = "raw";
});
//

//Populate HTML_ELEMENT
var all = constants.HTML_SPAN_ELEMENTS.concat(constants.HTML_BLOCK_ELEMENTS).concat(constants.HTML_ELEMENTS_WITHOUT_BODY).concat(constants.HTML_CONTENT_MODEL);

all.forEach(function(entry) {
    constants.HTML_ELEMENT[entry] = true;
});